# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GarminIMG
                                 A QGIS plugin
 Export IMG pour appareils Garmin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-11
        copyright            : (C) 2026 by JFB
        email                : jessicaf.bolduc@horizon-sf.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GarminIMG class from file GarminIMG.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .garmin_img import GarminIMG
    return GarminIMG(iface)
