# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GarminIMGDialog
                                 A QGIS plugin
 Export IMG pour appareils Garmin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by JFB
        email                : jessicaf.bolduc@horizon-sf.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import html

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'garmin_img_dialog_base.ui'),
    from_imports=True,
    import_from='garmin_img')


class GarminIMGDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GarminIMGDialog, self).__init__(parent)
        self.setupUi(self)

        # Section "Paramètres avancés" repliable, fermée par défaut
        self.frmAdvanced.setVisible(False)
        self.btnAdvance.toggled.connect(self._on_advanced_toggled)

    def _on_advanced_toggled(self, checked):
        self.frmAdvanced.setVisible(checked)
        self.btnAdvance.setArrowType(
            Qt.DownArrow if checked else Qt.RightArrow
        )

    def log_info(self, message):
        safe_message = html.escape(message)
        self.journal.append(f'<span style="color:#000000;">{safe_message}</span>')

    def log_success(self, message):
        safe_message = html.escape(message)
        self.journal.append(f'<span style="color:#008000;">✓ {safe_message}</span>')

    def log_error(self, message):
        safe_message = html.escape(message)
        self.journal.append(f'<span style="color:#cc0000;">✗ {safe_message}</span>')

    def log_warning(self, message):
        safe_message = html.escape(message)
        self.journal.append(f'<span style="color:#cc8800;">⚠ {safe_message}</span>')